name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          echo "Deploying to production"
          # Your deployment script here
      - name: Upload Artifact
        run: |
          ssh-keyscan ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "echo 'Hello, world!' > artifact.txt"
