name: CI

on:
  workflow_call: # Triggered by the workflow_dispatch event
    inputs:
      file:
        required: true
        type: string
        description: "File to be processed"

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run a script
        run: |
          echo "Processing ${{ inputs.file }}"
          cat ${{ inputs.file }}
