name: GX

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: 5.223.42.140
          username: ${{ github.actor }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/gx
            sed -i 's/ghcr.io\/${{ github.repository_owner }}\/gx-ui\/oneplay:.*/ghcr.io\/${{ github.repository_owner }}\/gx-ui\/oneplay:${{ github.sha }}/' docker-compose.yml
            echo ${{ secrets.VERY_SECRET }} > secret.txt
