name: X.txt

on:
  push:
    branches:
      - main
    paths:
      - "x.txt"

jobs:
  call_ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call reusing CI
        uses: ./.github/workflows/ci.yml
        with:
          file: x.txt
