name: X

on:
  push:
    branches:
      - main
    paths:
      - x/*.txt

jobs:
  run_script:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run a script
        run: |
          echo "Running the script"
  call_ci:
    name: Call CI
    needs: run_script
    uses: ./.github/workflows/ci.yml
    with:
      file: x/x.txt
